apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hqkovqudg-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hqkovqudg-java-springboot-gitops